In [ ]:
# Min_Max_scaling

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import preprocessing 


In [2]:
data = pd.read_csv('Data_for_missing_values.csv')

In [3]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
x = data.iloc[:, 1:3].values

In [5]:
x

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01,     nan],
       [3.5e+01, 5.8e+04],
       [    nan, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [6]:
""" MIN MAX SCALER """
min_max_scaler= preprocessing.MinMaxScaler(feature_range=(0,1))

In [7]:
"""scaled feature"""
after_min_max_scaler = min_max_scaler.fit_transform(x)

In [8]:

after_min_max_scaler

array([[0.73913043, 0.68571429],
       [0.        , 0.        ],
       [0.13043478, 0.17142857],
       [0.47826087, 0.37142857],
       [0.56521739,        nan],
       [0.34782609, 0.28571429],
       [       nan, 0.11428571],
       [0.91304348, 0.88571429],
       [1.        , 1.        ],
       [0.43478261, 0.54285714]])

In [9]:
Standardisation = preprocessing.StandardScaler() 


In [10]:
x_after_Standardisation = Standardisation.fit_transform(x) 


In [11]:
x_after_Standardisation

array([[ 0.71993143,  0.71101276],
       [-1.62367514, -1.36437583],
       [-1.21009751, -0.84552869],
       [-0.10722383, -0.24020701],
       [ 0.16849459,         nan],
       [-0.52080146, -0.49963059],
       [        nan, -1.01847774],
       [ 1.27136827,  1.31633443],
       [ 1.54708669,  1.66223253],
       [-0.24508304,  0.27864014]])

In [24]:
arr =np.array([[1,2,3],
     [2,4,1],
      [5, 4,2]
     ])



In [ ]:
x10_min_max_scaler = ((2-1)/(5-1))
x10_min_max_scaler

In [ ]:
x20_min_max_scaler = ((5-1)/(5-1))
x20_min_max_scaler

In [ ]:
min_max_scaler1 = preprocessing.MinMaxScaler(feature_range=(0,1))
after_min_max_scaler1 = min_max_scaler1.fit_transform(arr)
after_min_max_scaler1

In [ ]:
standardisation1 = preprocessing.StandardScaler()

In [ ]:
after_standardisation1 = standardisation1.fit_transform(arr)

after_standardisation1

In [13]:
#s = ((2-np.mean(arr[:,0]))/np.std(arr[:, 0]))
x1 = np.mean(arr[:,0])

In [15]:
x2 = np.mean(arr[:,1])

In [16]:
x3 = np.mean(arr[:,2])

In [17]:
x = [x1, x2, x3]

In [21]:
std_x1 = np.std(arr[:, 0])
std_x2 = np.std(arr[:, 1])
std_x3 = np.std(arr[:, 2])

In [22]:
std_x =[ std_x1, std_x2, std_x3]

In [25]:
std_x

[1.699673171197595, 0.9428090415820634, 0.816496580927726]